//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProducerInterfaceCommon.ContextModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountCompany
    {
        public AccountCompany()
        {
            this.CompanyDomainName = new HashSet<CompanyDomainName>();
            this.Account = new HashSet<Account>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<long> ProducerId { get; set; }
    
        public virtual ICollection<CompanyDomainName> CompanyDomainName { get; set; }
        public virtual ICollection<Account> Account { get; set; }
    }
}
