//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using ProducerInterfaceCommon.Models;

namespace ProducerInterfaceCommon.ContextModels
{
    using System;
    using System.Collections.Generic;

    public partial class Account
    {
        public Account()
        {
            this.AccountEmail = new HashSet<AccountEmail>();
            this.AccountRegion = new HashSet<AccountRegion>();
            this.AccountFeedBackComment = new HashSet<AccountFeedBackComment>();
            this.AccountFeedBack = new HashSet<AccountFeedBack>();
            this.AccountFeedBack1 = new HashSet<AccountFeedBack>();
            this.NewsChange = new HashSet<NewsChange>();
            this.AccountGroup = new HashSet<AccountGroup>();
            this.promotions = new HashSet<Promotion>();
        }

        public long Id { get; set; }
        public string Login { get; set; }
        public Nullable<int> AppointmentId { get; set; }
        public sbyte TypeUser { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string OtherName { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
        public string Appointment { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public Nullable<System.DateTime> PasswordUpdated { get; set; }
        public sbyte Enabled { get; set; }
        public Nullable<System.DateTime> LastUpdatePermisison { get; set; }
        public Nullable<System.DateTime> SecureTime { get; set; }

        public virtual AccountAppointment AccountAppointment { get; set; }
        public virtual AccountCompany AccountCompany { get; set; }
        public virtual ICollection<AccountEmail> AccountEmail { get; set; }
        public virtual ICollection<AccountRegion> AccountRegion { get; set; }
        public virtual ICollection<AccountFeedBackComment> AccountFeedBackComment { get; set; }
        public virtual ICollection<AccountFeedBack> AccountFeedBack { get; set; }
        public virtual ICollection<AccountFeedBack> AccountFeedBack1 { get; set; }
        public virtual ICollection<NewsChange> NewsChange { get; set; }
        public virtual ICollection<AccountGroup> AccountGroup { get; set; }
        public virtual ICollection<Promotion> promotions { get; set; }
    }
}
