//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProducerInterfaceCommon.ContextModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountAppointment
    {
        public AccountAppointment()
        {
            this.Account = new HashSet<Account>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<sbyte> GlobalEnabled { get; set; }
        public Nullable<long> IdAccount { get; set; }
    
        public virtual ICollection<Account> Account { get; set; }
        public virtual Account Account1 { get; set; }
    }
}
