//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProducerInterfaceCommon.ContextModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogLog
    {
        public long Id { get; set; }
        public System.DateTime LogTime { get; set; }
        public long UserId { get; set; }
        public string OperatorHost { get; set; }
        public long ObjectReference { get; set; }
        public string ObjectReferenceNameUi { get; set; }
        public int Type { get; set; }
        public string PropertyName { get; set; }
        public string PropertyNameUi { get; set; }
        public string Before { get; set; }
        public string After { get; set; }
        public bool Apply { get; set; }
        public Nullable<long> AdminId { get; set; }
        public Nullable<System.DateTime> DateEdit { get; set; }
    }
}
