//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProducerInterfaceCommon.ContextModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class cataloglogview
    {
        public long Id { get; set; }
        public System.DateTime LogTime { get; set; }
        public string OperatorName { get; set; }
        public string OperatorHost { get; set; }
        public Nullable<byte> Operation { get; set; }
        public Nullable<long> CatalogId { get; set; }
        public Nullable<bool> NewVitallyImportant { get; set; }
        public Nullable<bool> OldVitallyImportant { get; set; }
        public Nullable<bool> NewMandatoryList { get; set; }
        public Nullable<bool> OldMandatoryList { get; set; }
        public Nullable<bool> NewMonobrend { get; set; }
        public Nullable<bool> OldMonobrend { get; set; }
        public Nullable<bool> NewNarcotic { get; set; }
        public Nullable<bool> OldNarcotic { get; set; }
        public Nullable<bool> NewToxic { get; set; }
        public Nullable<bool> OldToxic { get; set; }
        public Nullable<bool> NewCombined { get; set; }
        public Nullable<bool> OldCombined { get; set; }
        public Nullable<bool> NewOther { get; set; }
        public Nullable<bool> OldOther { get; set; }
    }
}
