//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProducerInterfaceCommon.ContextModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalognameswithuptime
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<long> DescriptionId { get; set; }
        public Nullable<long> MnnId { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
