//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProducerInterfaceCommon.ContextModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogLog
    {
        public long Id { get; set; }
        public long NameId { get; set; }
        public System.DateTime LogTime { get; set; }
        public long UserId { get; set; }
        public string OperatorHost { get; set; }
        public long ObjectReference { get; set; }
        public string ObjectReferenceNameUi { get; set; }
        public int Type { get; set; }
        public string PropertyName { get; set; }
        public string PropertyNameUi { get; set; }
        public string Before { get; set; }
        public string After { get; set; }
        public sbyte Apply { get; set; }
        public Nullable<long> AdminId { get; set; }
        public Nullable<System.DateTime> DateEdit { get; set; }
        public Nullable<long> ProducerId { get; set; }
    }
}
