//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProducerInterfaceCommon.ContextModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrugDescriptionRemark
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string EnglishName { get; set; }
        public string Description { get; set; }
        public string Interaction { get; set; }
        public string SideEffect { get; set; }
        public string IndicationsForUse { get; set; }
        public string Dosing { get; set; }
        public string Warnings { get; set; }
        public string ProductForm { get; set; }
        public string PharmacologicalAction { get; set; }
        public string Storage { get; set; }
        public string Expiration { get; set; }
        public string Composition { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<long> ModificatorId { get; set; }
        public Nullable<long> ProducerUserId { get; set; }
        public Nullable<long> DrugFamilyId { get; set; }
        public Nullable<long> MNNId { get; set; }
    }
}
