//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProducerInterfaceCommon.ContextModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class drugformproducer
    {
        public long CatalogId { get; set; }
        public long ProducerId { get; set; }
        public long DrugFamilyId { get; set; }
        public string CatalogName { get; set; }
        public bool VitallyImportant { get; set; }
        public bool MandatoryList { get; set; }
        public bool Monobrend { get; set; }
        public bool Narcotic { get; set; }
        public bool Toxic { get; set; }
        public bool Combined { get; set; }
    }
}
