//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProducerInterfaceCommon.ContextModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedbackui
    {
        public long Id { get; set; }
        public Nullable<long> AccountId { get; set; }
        public string Login { get; set; }
        public Nullable<long> ProducerId { get; set; }
        public string ProducerName { get; set; }
        public string Contacts { get; set; }
        public System.DateTime DateAdd { get; set; }
        public string Description { get; set; }
        public sbyte Status { get; set; }
        public string UrlString { get; set; }
        public sbyte Type { get; set; }
    }
}
