//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using ProducerInterfaceCommon.Models;

namespace ProducerInterfaceCommon.ContextModels
{
    using System;
    using System.Collections.Generic;

    public partial class MediaFiles
    {
        public MediaFiles()
        {
            this.mailform = new HashSet<mailform>();
        }

        public int Id { get; set; }
        public string ImageName { get; set; }
        public byte[] ImageFile { get; set; }
        public string ImageType { get; set; }
        public string ImageSize { get; set; }
        public int EntityType { get; set; }

        public virtual ICollection<mailform> mailform { get; set; }
    }
}
