//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProducerInterfaceCommon.ContextModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationToProducers
    {
        public NotificationToProducers()
        {
            this.NewsChange = new HashSet<NewsChange>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DatePublication { get; set; }
        public bool Enabled { get; set; }
    
        public virtual ICollection<NewsChange> NewsChange { get; set; }
    }
}
