//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProducerInterfaceCommon.ContextModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProducerUser
    {
        public ProducerUser()
        {
            this.DrugDescriptionRemark = new HashSet<DrugDescriptionRemark>();
            this.promotions = new HashSet<promotions>();
            this.user_logs = new HashSet<user_logs>();
            this.usertouserrole = new HashSet<usertouserrole>();
            this.ControlPanelGroup = new HashSet<ControlPanelGroup>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Appointment { get; set; }
        public Nullable<long> ProducerId { get; set; }
        public Nullable<System.DateTime> PasswordUpdated { get; set; }
        public Nullable<sbyte> PasswordToUpdate { get; set; }
        public Nullable<sbyte> Enabled { get; set; }
        public string Login { get; set; }
    
        public virtual ICollection<DrugDescriptionRemark> DrugDescriptionRemark { get; set; }
        public virtual ICollection<promotions> promotions { get; set; }
        public virtual ICollection<user_logs> user_logs { get; set; }
        public virtual ICollection<usertouserrole> usertouserrole { get; set; }
        public virtual ICollection<ControlPanelGroup> ControlPanelGroup { get; set; }
    }
}
