//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProducerInterfaceCommon.ContextModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class profilenews
    {
        public long Id { get; set; }
        public string Topic { get; set; }
        public string Text { get; set; }
        public Nullable<long> ProducerId { get; set; }
        public System.DateTime EditedDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
