//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProducerInterfaceCommon.ContextModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class propertychangeview
    {
        public int ChangePropertyId { get; set; }
        public int ChangeObjectId { get; set; }
        public string PropertyName { get; set; }
        public string ValueOld { get; set; }
        public string ValueNew { get; set; }
        public string TypeName { get; set; }
    }
}
