//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quartz.Job.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class regionnames
    {
        public decimal RegionCode { get; set; }
        public string RegionName { get; set; }
    }
}
