//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quartz.Job.EDM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class reportData : DbContext
    {
        public reportData()
            : base("name=reportData")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<producernames> producernames { get; set; }
        public virtual DbSet<suppliernames> suppliernames { get; set; }
        public virtual DbSet<regionnames> regionnames { get; set; }
        public virtual DbSet<pharmacynames> pharmacynames { get; set; }
        public virtual DbSet<assortment> assortment { get; set; }
        public virtual DbSet<catalognames> catalognames { get; set; }
        public virtual DbSet<usernames> usernames { get; set; }
        public virtual DbSet<jobextend> jobextend { get; set; }
        public virtual DbSet<reportxml> reportxml { get; set; }
        public virtual DbSet<mailformwithfooter> mailformwithfooter { get; set; }
    }
}
