//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quartz.Job.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class usernames
    {
        public long UserId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public long ProducerId { get; set; }
        public string ProducerName { get; set; }
    }
}
