//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProducerInterfaceControlPanelDomain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlPanelUser
    {
        public ControlPanelUser()
        {
            this.ControlPanelGroup = new HashSet<ControlPanelGroup>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Appointment { get; set; }
        public sbyte Enabled { get; set; }
        public string FullName { get; set; }
    
        public virtual ICollection<ControlPanelGroup> ControlPanelGroup { get; set; }
    }
}
