//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProducerInterfaceControlPanelDomain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlPanelGroup
    {
        public ControlPanelGroup()
        {
            this.ControlPanelPermission = new HashSet<ControlPanelPermission>();
            this.ControlPanelUser = new HashSet<ControlPanelUser>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public bool Enabled { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<ControlPanelPermission> ControlPanelPermission { get; set; }
        public virtual ICollection<ControlPanelUser> ControlPanelUser { get; set; }
    }
}
