//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProducerInterfaceControlPanelDomain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class controlpaneluserpermission
    {
        public string Name { get; set; }
        public string Email { get; set; }
        public string Appointment { get; set; }
        public sbyte Enabled { get; set; }
        public long IdUser { get; set; }
        public long IdGroup { get; set; }
        public string GroupName { get; set; }
        public long IdPermission { get; set; }
        public string ControllerAction { get; set; }
        public string ActionAttributes { get; set; }
        public string Description { get; set; }
        public bool Enable_Group { get; set; }
        public bool Enable_Permission { get; set; }
    }
}
