//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProducerInterfaceControlPanelDomain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class drugmnn
    {
        public long DrugFamilyId { get; set; }
        public string DrugFamilyName { get; set; }
        public Nullable<long> MnnId { get; set; }
        public string Mnn { get; set; }
        public string RussianMnn { get; set; }
    }
}
