use producerinterface;
ALTER TABLE `users`
	DROP FOREIGN KEY `producerUser_key`;
	
CREATE TABLE `drugdescriptionremark` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Name` VARCHAR(255) NULL DEFAULT NULL,
	`EnglishName` VARCHAR(255) NULL DEFAULT NULL,
	`Description` VARCHAR(255) NULL DEFAULT NULL,
	`Interaction` VARCHAR(255) NULL DEFAULT NULL,
	`SideEffect` VARCHAR(255) NULL DEFAULT NULL,
	`IndicationsForUse` VARCHAR(255) NULL DEFAULT NULL,
	`Dosing` VARCHAR(255) NULL DEFAULT NULL,
	`Warnings` VARCHAR(255) NULL DEFAULT NULL,
	`ProductForm` VARCHAR(255) NULL DEFAULT NULL,
	`PharmacologicalAction` VARCHAR(255) NULL DEFAULT NULL,
	`Storage` VARCHAR(255) NULL DEFAULT NULL,
	`Expiration` VARCHAR(255) NULL DEFAULT NULL,
	`Composition` VARCHAR(255) NULL DEFAULT NULL,
	`CreationDate` DATETIME NULL DEFAULT NULL,
	`Status` INT(11) NULL DEFAULT NULL,
	`ModificationDate` DATETIME NULL DEFAULT NULL,
	`ModificatorId` INT(11) UNSIGNED NULL DEFAULT NULL,
	`ProducerUserId` INT(11) UNSIGNED NULL DEFAULT NULL,
	`DrugFamilyId` INT(11) UNSIGNED NULL DEFAULT NULL,
	`MNNId` INT(11) UNSIGNED NULL DEFAULT NULL,
	PRIMARY KEY (`Id`)
)
COLLATE='cp1251_general_ci'
ENGINE=InnoDB;
