use producerinterface;
CREATE TABLE `reporttemplate` (
	`Id` INT(11) NOT NULL AUTO_INCREMENT,
	`Title` VARCHAR(255) NULL DEFAULT NULL,
	`Type` INT(11) NULL DEFAULT NULL,
	`GeneralReportId` INT(11) NULL DEFAULT NULL,
	`UserId` INT(11) NULL DEFAULT NULL,
	`Modificator` INT(11) NULL DEFAULT NULL,
	`CreationDate` DATETIME NULL DEFAULT NULL,
	`ModificationDate` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`Id`)
)
COLLATE='cp1251_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=6
;
