use producerinterface;
CREATE TABLE `slides` (
	`Id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`Url` VARCHAR(255) NULL DEFAULT NULL,
	`ImagePath` INT(11) UNSIGNED NULL DEFAULT NULL,
	`LastEdit` DATETIME NULL DEFAULT NULL,
	`Enabled` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1',
	`PositionIndex` INT(11) UNSIGNED NULL DEFAULT NULL,
	PRIMARY KEY (`Id`)
);