//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProducerInterfaceCommon.LogsModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogLogs
    {
        public long Id { get; set; }
        public System.DateTime LogTime { get; set; }
        public string OperatorName { get; set; }
        public string OperatorHost { get; set; }
        public Nullable<byte> Operation { get; set; }
        public Nullable<long> CatalogId { get; set; }
        public Nullable<long> FormId { get; set; }
        public Nullable<long> NameId { get; set; }
        public Nullable<bool> VitallyImportant { get; set; }
        public Nullable<bool> NeedCold { get; set; }
        public Nullable<bool> Fragile { get; set; }
        public Nullable<bool> Hidden { get; set; }
        public Nullable<bool> MandatoryList { get; set; }
        public Nullable<bool> Pharmacie { get; set; }
        public string Name { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public Nullable<bool> Monobrend { get; set; }
        public Nullable<long> NewFormId { get; set; }
        public Nullable<long> OldFormId { get; set; }
        public Nullable<long> NewNameId { get; set; }
        public Nullable<long> OldNameId { get; set; }
        public Nullable<bool> NewVitallyImportant { get; set; }
        public Nullable<bool> OldVitallyImportant { get; set; }
        public Nullable<bool> NewMandatoryList { get; set; }
        public Nullable<bool> OldMandatoryList { get; set; }
        public Nullable<bool> NewNeedCold { get; set; }
        public Nullable<bool> OldNeedCold { get; set; }
        public Nullable<bool> NewFragile { get; set; }
        public Nullable<bool> OldFragile { get; set; }
        public Nullable<bool> NewPharmacie { get; set; }
        public Nullable<bool> OldPharmacie { get; set; }
        public Nullable<bool> NewHidden { get; set; }
        public Nullable<bool> OldHidden { get; set; }
        public string NewName { get; set; }
        public string OldName { get; set; }
        public System.DateTime NewUpdateTime { get; set; }
        public System.DateTime OldUpdateTime { get; set; }
        public Nullable<bool> NewMonobrend { get; set; }
        public Nullable<bool> OldMonobrend { get; set; }
        public Nullable<bool> NewNarcotic { get; set; }
        public Nullable<bool> OldNarcotic { get; set; }
        public Nullable<bool> NewToxic { get; set; }
        public Nullable<bool> OldToxic { get; set; }
        public Nullable<bool> NewCombined { get; set; }
        public Nullable<bool> OldCombined { get; set; }
        public Nullable<bool> NewOther { get; set; }
        public Nullable<bool> OldOther { get; set; }
    }
}
