//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProducerInterfaceCommon.LogsModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class descriptionlogs
    {
        public long Id { get; set; }
        public System.DateTime LogTime { get; set; }
        public string OperatorName { get; set; }
        public string OperatorHost { get; set; }
        public byte Operation { get; set; }
        public long DescriptionId { get; set; }
        public string Name { get; set; }
        public string EnglishName { get; set; }
        public string Description { get; set; }
        public string Interaction { get; set; }
        public string SideEffect { get; set; }
        public string IndicationsForUse { get; set; }
        public string Dosing { get; set; }
        public string Warnings { get; set; }
        public string ProductForm { get; set; }
        public string PharmacologicalAction { get; set; }
        public string Storage { get; set; }
        public string Expiration { get; set; }
        public string Composition { get; set; }
        public Nullable<bool> NeedCorrect { get; set; }
    }
}
