//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProducerInterfaceCommon.LoggerModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class logchangeview
    {
        public int ChangeSetId { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string Ip { get; set; }
        public long UserId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public long ProducerId { get; set; }
        public string ProducerName { get; set; }
        public Nullable<int> ChangeObjectId { get; set; }
        public Nullable<int> Action { get; set; }
        public string TypeName { get; set; }
    }
}
