//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProducerInterfaceCommon.LoggerModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogPropertyChange
    {
        public int Id { get; set; }
        public string PropertyName { get; set; }
        public string ValueOld { get; set; }
        public string ValueNew { get; set; }
        public int LogObjectChangeId { get; set; }
    
        public virtual LogObjectChange LogObjectChange { get; set; }
    }
}
