//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProducerInterfaceCommon.ReportModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class enum_values
    {
        public decimal ID { get; set; }
        public decimal PropertyEnumID { get; set; }
        public int Value { get; set; }
        public string DisplayValue { get; set; }
    
        public virtual property_enums property_enums { get; set; }
    }
}
