//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProducerInterfaceCommon.ReportModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class general_reports
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public general_reports()
        {
            this.reports = new HashSet<reports>();
        }
    
        public decimal GeneralReportCode { get; set; }
        public Nullable<long> FirmCode { get; set; }
        public bool Allow { get; set; }
        public string EMailSubject { get; set; }
        public string ReportFileName { get; set; }
        public string ReportArchName { get; set; }
        public Nullable<long> ContactGroupId { get; set; }
        public bool Temporary { get; set; }
        public Nullable<System.DateTime> TemporaryCreationDate { get; set; }
        public string Comment { get; set; }
        public Nullable<long> PayerID { get; set; }
        public string Format { get; set; }
        public Nullable<bool> NoArchive { get; set; }
        public Nullable<long> OwnedByUser { get; set; }
        public bool SendDescriptionFile { get; set; }
        public bool Public { get; set; }
        public Nullable<System.DateTime> LastSuccess { get; set; }
        public Nullable<long> PublicSubscriptionsId { get; set; }
        public bool MailPerFile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reports> reports { get; set; }
    }
}
