//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProducerInterfaceCommon.ReportModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class report_property_values
    {
        public decimal ID { get; set; }
        public decimal ReportPropertyID { get; set; }
        public string Value { get; set; }
    
        public virtual report_properties report_properties { get; set; }
    }
}
