//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProducerInterfaceCommon.ReportModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class reportsEntities : DbContext
    {
        public reportsEntities()
            : base("name=reportsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<enum_values> enum_values { get; set; }
        public virtual DbSet<general_reports> general_reports { get; set; }
        public virtual DbSet<property_enums> property_enums { get; set; }
        public virtual DbSet<report_properties> report_properties { get; set; }
        public virtual DbSet<report_property_values> report_property_values { get; set; }
        public virtual DbSet<report_type_properties> report_type_properties { get; set; }
        public virtual DbSet<reports> reports { get; set; }
        public virtual DbSet<reporttypes> reporttypes { get; set; }
    }
}
