//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProducerInterfaceCommon.ReportModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class report_properties
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public report_properties()
        {
            this.report_property_values = new HashSet<report_property_values>();
        }
    
        public decimal ID { get; set; }
        public decimal ReportCode { get; set; }
        public decimal PropertyID { get; set; }
        public string PropertyValue { get; set; }
    
        public virtual report_type_properties report_type_properties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<report_property_values> report_property_values { get; set; }
        public virtual reports reports { get; set; }
    }
}
