//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProducerInterfaceCommon.ReportModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class reporttypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public reporttypes()
        {
            this.report_type_properties = new HashSet<report_type_properties>();
            this.reports = new HashSet<reports>();
        }
    
        public decimal ReportTypeCode { get; set; }
        public string ReportTypeName { get; set; }
        public string ReportTypeFilePrefix { get; set; }
        public string AlternateSubject { get; set; }
        public string ReportClassName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<report_type_properties> report_type_properties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reports> reports { get; set; }
    }
}
