//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProducerInterfaceCommon.ReportModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class reports
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public reports()
        {
            this.report_properties = new HashSet<report_properties>();
        }
    
        public decimal ReportCode { get; set; }
        public decimal GeneralReportCode { get; set; }
        public string ReportCaption { get; set; }
        public decimal ReportTypeCode { get; set; }
        public bool Enabled { get; set; }
    
        public virtual general_reports general_reports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<report_properties> report_properties { get; set; }
        public virtual reporttypes reporttypes { get; set; }
    }
}
