//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProducerInterfaceCommon.ReportModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class report_type_properties
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public report_type_properties()
        {
            this.report_properties = new HashSet<report_properties>();
        }
    
        public decimal ID { get; set; }
        public decimal ReportTypeCode { get; set; }
        public string PropertyName { get; set; }
        public string DisplayName { get; set; }
        public string PropertyType { get; set; }
        public bool Optional { get; set; }
        public Nullable<decimal> PropertyEnumID { get; set; }
        public string SelectStoredProcedure { get; set; }
        public string DefaultValue { get; set; }
    
        public virtual property_enums property_enums { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<report_properties> report_properties { get; set; }
        public virtual reporttypes reporttypes { get; set; }
    }
}
