//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityContext.ContextModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class controlpaneluserpermission
    {
        public string Name { get; set; }
        public string Email { get; set; }
        public string Appointment { get; set; }
        public sbyte Enabled { get; set; }
        public Nullable<long> IdUser { get; set; }
        public Nullable<long> IdGroup { get; set; }
        public string GroupName { get; set; }
        public Nullable<long> IdPermission { get; set; }
        public string ControllerAction { get; set; }
        public string ActionAttributes { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Enable_Group { get; set; }
        public sbyte Enable_Permission { get; set; }
    }
}
