//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityContext.ContextModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class pharmacynames
    {
        public long PharmacyId { get; set; }
        public string PharmacyName { get; set; }
    }
}
