//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityContext.ContextModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class produceruserpermission
    {
        public long userId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public sbyte Enabled { get; set; }
        public Nullable<System.DateTime> PasswordUpdated { get; set; }
        public Nullable<long> ProducerId { get; set; }
        public Nullable<long> UserPermissionId { get; set; }
        public Nullable<long> roleId { get; set; }
        public string roleName { get; set; }
    }
}
