//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityContext.ContextModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class usertouserrole
    {
        public Nullable<long> ProducerUserId { get; set; }
        public Nullable<long> UserRoleId { get; set; }
        public Nullable<long> UserPermissionId { get; set; }
        public long Id { get; set; }
    
        public virtual ProducerUser ProducerUser { get; set; }
        public virtual ProducerUser ProducerUser1 { get; set; }
        public virtual UserPermission UserPermission { get; set; }
        public virtual UserPermission UserPermission1 { get; set; }
        public virtual userrole userrole { get; set; }
    }
}
