//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProducerInterface.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class producerinterface_Entities : DbContext
    {
        public producerinterface_Entities()
            : base("name=producerinterface_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<drugdescriptionremark> drugdescriptionremark { get; set; }
        public DbSet<producers> producers { get; set; }
        public DbSet<produceruser> produceruser { get; set; }
        public DbSet<profilenews> profilenews { get; set; }
        public DbSet<promotions> promotions { get; set; }
        public DbSet<reporttemplate> reporttemplate { get; set; }
        public DbSet<user_logs> user_logs { get; set; }
        public DbSet<userpermission> userpermission { get; set; }
        public DbSet<userrole> userrole { get; set; }
        public DbSet<usertouserrole> usertouserrole { get; set; }
        public DbSet<promotiontodrug> promotiontodrug { get; set; }
        public DbSet<userpermissionrole> userpermissionrole { get; set; }
        public DbSet<producernames> producernames { get; set; }
        public DbSet<produserslist> produserslist { get; set; }
    }
}
