//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProducerInterface.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class promotions
    {
        public promotions()
        {
            this.promotiontodrug = new HashSet<promotiontodrug>();
            this.promotiontodrug1 = new HashSet<promotiontodrug>();
        }
    
        public long Id { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public bool Enabled { get; set; }
        public Nullable<long> AdminId { get; set; }
        public long ProducerId { get; set; }
        public long ProducerUserId { get; set; }
        public string Annotation { get; set; }
        public string PromoFile { get; set; }
        public bool AgencyDisabled { get; set; }
        public string Name { get; set; }
        public decimal RegionMask { get; set; }
        public Nullable<System.DateTime> Begin { get; set; }
        public Nullable<System.DateTime> End { get; set; }
        public bool Status { get; set; }
    

        [UIHint("LongList")]
        public virtual List<long> DrugList { get; set; }
        public virtual produceruser produceruser { get; set; }
        public virtual produceruser produceruser1 { get; set; }
        public virtual ICollection<promotiontodrug> promotiontodrug { get; set; }
        public virtual ICollection<promotiontodrug> promotiontodrug1 { get; set; }
    }
}
