//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProducerInterface.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reporttemplate
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> GeneralReportId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> Modificator { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
    }
}
